#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-222"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "719452a4c51c45809682e8ef2b5a1e89" }
]

[assets]
directory = "./public"
